%% Configuration

global aircraft g recording config

%General configuration
config.UseTheAirbus=0; %If 1, A300 will be forced. else, the selected FDM will be used
g = 9.81; %Gravity Acceleration, m/s^2

%Set fsolve options
options = optimset('Display','on','TolX',1e-6,'TolFun',1e-6); %,'MaxFunEvals',1300

%% INITIALIZE

% clear all
% close all
clc

disp(' ')
disp('Ciclon Alpha C1')
disp('Initialization...')

recording=[];

config.CAFile=GDT.DataLoadName;
config.CFFile=GDT.FCLoadName;
FCT=GDT.SFC;

% %Aileron command
% config.maneouver=1; %0 for fixed, 1 for single input, 2 for doublet
%
% config.ap=5*pi/180; %Command deflection
% config.ti=1; %initial time
% config.tf=2; %final time
% config.td=(config.ti+config.tf)/2; %doublet switchover time

%% Load Aircraft Data

if config.UseTheAirbus == 1
    %%%%% A300
    aircraft = struct(  'S',260,...
        'c',6.6,...
        'b',44.8,...
        'm',130000,...
        'Iyy',10.53e6,...
        'Izz',15.73e6,...
        'Ixz',0.33e6,...
        'Ixx',6.011e6,...
        'i_p_rad',2.17*pi/180,...
        't_p_rad',0*pi/180,...
        'x_p',0,...
        'y_p',0,...
        'z_p',2.65); %Airbus A300
    disp(' ')
    disp('Aircraft Model: Airbus A300')
    
    Op_Points(1) = struct(  'V',77,...
        'h',600,...
        'gamma_rad',-3*pi/180,...
        'psidot_rad_s',0*pi/180,...
        'thetadot_rad_s',0); %A300 A1
    Op_Points(2) = struct(  'V',131.5,...
        'h',3000,...
        'gamma_rad',0,...
        'psidot_rad_s',0*pi/180,...
        'thetadot_rad_s',0); %A300 A2
    Op_Points(3) = struct(  'V',264,...
        'h',10000,...
        'gamma_rad',0*pi/180,...
        'psidot_rad_s',0*pi/180,...
        'thetadot_rad_s',0*pi/180); %A300 A3
    disp(' ')
    disp('Flight Conditions loaded')
else
    %% (LEV / MTN)
    
    load(config.CAFile)
    
    aircraft = struct(  'S',Datum.S_ref,...
        'c',Datum.C_mac,...
        'b',Datum.b_ref,...
        'm',Inertial_Data.Aircraft_Mass_Fixed,...
        'Iyy',Inertial_Data.Inertia_Matrix_Fixed(2,2),...
        'Izz',Inertial_Data.Inertia_Matrix_Fixed(3,3),...
        'Ixz',Inertial_Data.Inertia_Matrix_Fixed(1,3),... %Atento! signo...
        'Ixx',Inertial_Data.Inertia_Matrix_Fixed(1,1),...
        'i_p_rad',0*pi/180,...
        't_p_rad',0*pi/180,...
        'x_p',0,...
        'y_p',0,...
        'z_p',0); %Loaded Aircraft
    
    disp(' ')
    fprintf('Aircraft: %-10s\n',General.AirName);
    fprintf('Description: %-10s\n',General.AirDescription);
    
    load(config.CFFile)
    
    disp(' ')
    fprintf('Current Flight name: %-10s\n',FlightGeneral.Name);
    fprintf('Current Flight condition: %-0s (%0.0f)\n',char(FlightNames(FCT)),FCT);
    
    disp(' ')
    disp('Flight Conditions loaded')
end